element:
  - title
  - description
  - link
  - pubDate
urls:
  - https://www.ansa.it/sito/ansait_rss.xml
  - https://www.ansa.it/sito/notizie/cronaca/cronaca_rss.xml
  - https://www.ansa.it/sito/notizie/politica/politica_rss.xml
  - https://www.ansa.it/sito/notizie/mondo/mondo_rss.xml
  - https://www.ansa.it/molise/notizie/molise_rss.xml
  - https://www.ansa.it/sito/notizie/economia/economia.shtml
  - https://www.ansa.it/sito/notizie/sport/calcio/calcio_rss.xml
  - https://www.ansa.it/sito/notizie/sport/sport_rss.xml
  - https://www.ansa.it/sito/notizie/cultura/cinema/cinema_rss.xml
  - https://www.ansa.it/sito/notizie/cultura/cultura_rss.xml
  - https://www.ansa.it/sito/notizie/tecnologia/tecnologia_rss.xml
  - https://www.ansa.it/sito/notizie/topnews/topnews_rss.xml
  - https://www.ansa.it/sito/notizie/topnews/topnews_rss.xml
  - https://www.ansa.it/sito/photogallery/foto_rss.xml
  - https://www.ansa.it/sito/videogallery/video_rss.xml
  - https://www.ansa.it/canale_ambiente/notizie/ambiente_rss.xml
  - https://www.ansa.it/canale_motori/notizie/motori_rss.xml
  - https://www.ansa.it/canale_lifestyle/notizie/lifestyle_rss.xml